CREATE TABLE customer (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255)
);

CREATE TABLE book (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	customer INTEGER REFERENCES customer(id),
	title VARCHAR(255),
	author VARCHAR(255)
);

